
services:
  order-service:
    image: quanghieu/order-service:latest
    depends_on:
      - order-consumer
    ports:
      - "8082:8082"
    networks:
      - order-service-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/orderdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: quanghieu
      SPRING_DATA_REDIS_HOST: host.docker.internal
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:9092

  order-consumer:
    image: quanghieu/order-consumer:latest
    networks:
      - order-service-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/orderdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: quanghieu
      SPRING_KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:9092

networks:
  order-service-network:
    driver: bridge
