spring:
  profiles:
      active: local
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://postgres:5432/orderdb  # tên service postgres trong docker-compose
    username: postgres
    password: quanghieu

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: kafka:9092  # tên service kafka

    consumer:
      group-id: order-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.example.order_service.entity"
        spring.json.value.default.type: "com.example.order_service.entity.Order"

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  cache:
    type: redis

  data:
    redis:
      host: redis
      port: 6379
      # password: your_redis_password (bỏ comment nếu Redis có password)

server:
  port: 8082
  address: 0.0.0.0
